[default]
src = 'contracts'
out = 'artifacts'
libs = ['node_modules']
remappings = [
    '@ensdomains/=node_modules/@ensdomains/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat-deploy/=node_modules/hardhat-deploy/',
    'hardhat/=node_modules/hardhat/',
]

# See more config options https://github.com/gakonst/foundry/tree/master/config
