on:
  push:
jobs:
  foundry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          recursive: true
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - run: |
          forge install
          forge test -vvvvv --gas-report
          forge snapshot --check
